//---------------------------------------------------------------------------------------
// Maximum possible value limit for Integer
// (Integer is 32-bits - same as INT32_MAX in C++)
// 
// Examples:
//   !big_num: Integer!max
//
//   // If type known, Integer can be omitted
//   42 = !max
//   42.min(!max)
//
// See: !min()
//---------------------------------------------------------------------------------------

() Integer 
  //[2147483647]
