//---------------------------------------------------------------------------------------
// Returns the absolute value of this number - makes it positive if it was negative.
// The original number remains unchanged.
//
// Returns: absolute value of itself
//
// Examples:
//   do_stuff(num.abs)
//   num := num.abs
//---------------------------------------------------------------------------------------

() Integer

