//---------------------------------------------------------------------------------------
// Description Returns the bitwise and of this value and the one supplied.
//             The original number remains unchanged.
// Returns     bitwise and of this value and the one supplied
// Examples    do_stuff(num1.bit_and(num2))
//             num1 := num1.bit_and(num2)
// Author(s)   Conan Reis
//---------------------------------------------------------------------------------------

(Integer num) Integer

