//---------------------------------------------------------------------------------------
// Copy constructor
//
// # Params:
//   vec: vector to copy
//
// # Returns: itself
//
// # Examples:
//   !vec1: Vector3!xyz(1 2 3)
//   !vec2: vec1!             // Recommended shortcut - same as code below
//   !vec3: vec1!copy
//   !vec4: Vector3!copy(vec1)
//
// # See:       Vector3!(), Vector3!xyz(), Vector3!xy()
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Vector3 vec) Vector3

