//---------------------------------------------------------------------------------------
// Constructor.  Initializes x and y values to supplied values and z to 0.
//
// # Params:
//   x: x value
//   y: y value
//
// # Returns: itself
//
// # Examples:
//   !vec: Vector3!xy(1 2)
//
// # See:       Vector3!(), Vector3!xyz(), Vector3!copy()
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real x, Real y) Vector3

