//---------------------------------------------------------------------------------------
// Returns the squared distance bewteen this vector and the origin (0, 0, 0) - also known
// as the squared magnitude.
//
// # Returns: squared distance between this vector and the origin
//
// # Examples:
//  !len_sq: vec.length_squared
//
// # See:       length(), distance(), distance_squared()
// # Notes:     This is a tiny bit faster than calling `length()`
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

() Real

