//---------------------------------------------------------------------------------------
// Returns the distance bewteen this vector and the origin (0, 0, 0) - also known as the
// magnitude of the vector.
//
// # Returns: distance between this vector and the origin
//
// # Examples:
//  !len: vec.length
//
// # See:       length_sq(), distance(), distance_squared()
// # Notes:     This is a tiny bit slower than calling `length_squared()`
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

() Real

