//---------------------------------------------------------------------------------------
// -= Subtracts supplied value from itself
//
// # Params:
//   vec: vector to subtract
//
// # Returns: itself
//
// # Examples:
//   vec1 -= vec2
//   vec1.subtract_assign(vec2)
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Vector3 vec) Vector3

