//---------------------------------------------------------------------------------------
// Copy constructor
//
// # Params:
//   vec: vector to copy
//
// # Returns: itself
//
// # Examples:
//   !vec1: Vector4!xyz(1 2 3)
//   !vec2: vec1!             // Recommended shortcut - same as code below
//   !vec3: vec1!copy
//   !vec4: Vector4!copy(vec1)
//
// # See:       Vector4!(), Vector4!xyz(), Vector4!xy()
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Vector4 vec) Vector4

