//---------------------------------------------------------------------------------------
// / Returns a new value that is itself divided by the supplied value.
//
// # Params:
//   operand: amount to divide each axis vaule by
//
// # Returns: new value that is itself divided by the supplied value.
//
// # Examples:
//   vec2: vec1 / 3
//   vec2: vec1.divide(3)
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real operand) Vector4

