//---------------------------------------------------------------------------------------
// - Returns a new vector that is itself minus the supplied vector.
//
// # Params:
//   vec: vector to subtract
//
// # Returns:
//   new vector that is itself minus the supplied vector.
//
// # Examples:
//   vec1 - vec2
//   vec1.subtract(vec2)
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Vector4 vec) Vector4

