//---------------------------------------------------------------------------------------
// [Same as ~= operator]
// Returns true if both objects are *not* logically the same.
//
// Examples:
//   obj1 ~= obj2
//   // or
//   obj1.not_equal?(obj2)
//
// See:
//   ```
//   =   equal?()
//       same?()        - tests if objects equivalent/same object in memory
//   :                  - bind operator - changes the object to which the variable refers
//   ```
//---------------------------------------------------------------------------------------

(Actor operand) Boolean

