//---------------------------------------------------------------------------------------
// Converts all the objects passed as arguments into strings, concatenates them, adds a
// newline (\n) and prints out the single concatenated string to the console.
// [Prints in Debug and *ignored* Release builds.]
//
// #Examples
//   Debug.print("The ultimate answer is: " 6 * 7)
//
// #See Also   print(), Object@print(), Object@println()
// #Author(s)  Conan Reis
//---------------------------------------------------------------------------------------

({Object} objs_as_strs)

