//---------------------------------------------------------------------------------------
// - Description
// operator + Concatenation.  Creates a copy of this list, appends specified list at its
// end, and returns it.
//
// - Notes
// This method allows duplicate items.
//
// - Examples
// {0, "one", 2.0} + {"three", 4}  // returns new list {0, "one", 2.0, "three", 4}
//
// - Author(s) Conan Reis
//---------------------------------------------------------------------------------------

(ThisClass_ list)
// new list that is this list concatenated with 'list'
ThisClass_

