//---------------------------------------------------------------------------------------
// Description Removes count items starting at index.  By default all items after and
//             including index are removed.
// Examples    {0, "one", 2.0, 3, "four"}.remove_range(1, 3)
//               changes list to {0, "four"}
// Author(s)   Conan Reis
//---------------------------------------------------------------------------------------

( Integer index,
  Integer count: length_after(index)
) ThisClass_




