//---------------------------------------------------------------------------------------
// Description Removes count items from the end of the list.
// Examples    {0, "one", 2.0, 3, "four"}.remove_range_last(3)
//               changes list to {0, "one"}
// Author(s)   Conan Reis
//---------------------------------------------------------------------------------------

(Integer count)
// Returns itself
ThisClass_



