//---------------------------------------------------------------------------------------
// Determines if the items in this list and the one supplied are the same/equivalent
// objects - i.e. same number and exact same item instances.
//
// #Author(s)   Conan Reis
//---------------------------------------------------------------------------------------

( // list to compare.  Note that a list with any class of items may be used.
  List list
) Boolean

