//---------------------------------------------------------------------------------------
// Default constructor.  Initializes x, y, z values to 0.0
//
// # Returns: itself
//
// # Examples:
//   !vec: Vector2!
//
// # See:       Vector2!xyz(), Vector2!xy(). Vector2!copy()
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

() Vector2

