//---------------------------------------------------------------------------------------
// Constructor.  Initializes x and y values to supplied values and z to 0.
//
// # Params:
//   x: x value
//   y: y value
//
// # Returns: itself
//
// # Examples:
//   !vec: Vector2!xy(1 2)
//
// # See:       Vector2!(), Vector2!xyz(), Vector2!copy()
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real x, Real y) Vector2

