//---------------------------------------------------------------------------------------
// Copy constructor
//
// #Examples
//   !val1: Random!
//   !val2: val1!      // Recommended shortcut - same as code below
//   !val3: val1!copy
//   !val4: Random!copy(val1)
//
// #Author(s)   Conan Reis
//---------------------------------------------------------------------------------------

(Random source)


