//---------------------------------------------------------------------------------------
// + Returns a new color that is the sum of itself and the supplied color.
//
// # Params:
//   col: color to add
//
// # Returns:
//   new color that is the sum of itself and the supplied color.
//
// # Examples:
//   col1 + col2
//   col1.add(col2)
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Color col) Color

