//---------------------------------------------------------------------------------------
// / Returns a new value that is itself divided by the supplied value.
//
// # Params:
//   operand: amount to divide each axis vaule by
//
// # Returns: new value that is itself divided by the supplied value.
//
// # Examples:
//   col2: col1 / 3
//   col2: col1.divide(3)
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real operand) Color

