//---------------------------------------------------------------------------------------
// /= Divides itself by supplied value
//
// # Params:
//   operand: amount to divide each axis vaule by
//
// # Returns: itself
//
// # Examples:
//   col /= 3
//   col.divide_assign(3)
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real operand) Color

