//---------------------------------------------------------------------------------------
// *= Multiplies itself by supplied value
//
// # Params:
//   operand: amount to multiply each axis value by
//
// # Returns: itself
//
// # Examples:
//   col *= 3
//   col.multiply_assign(3)
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real operand) Color

