//---------------------------------------------------------------------------------------
// - Returns a new color that is itself minus the supplied color.
//
// # Params:
//   col: color to subtract
//
// # Returns:
//   new color that is itself minus the supplied color.
//
// # Examples:
//   col1 - col2
//   col1.subtract(col2)
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Color col) Color

