//---------------------------------------------------------------------------------------
// Converter to a string representation of itself
//
// # Returns: itself as a string
//
// # Examples:
//   !str1: name.String
//   !str2: name>>String  // only converts name if it needs to
//
// # Author(s): Markus Breyer
//---------------------------------------------------------------------------------------

() String

