//---------------------------------------------------------------------------------------
// Converter to a string representation of itself
//
// # Returns: itself as a string
//
// # Examples:
//   !str1: transform.String
//   !str2: transform>>String  // only converts transform if it needs to
//
// # Notes:
//
// # Author(s): Markus Breyer
//---------------------------------------------------------------------------------------

() String
