//---------------------------------------------------------------------------------------
// Get the x-direction of this transform
//
// # Returns: Vector3 direction of the x-axis for this transform
//
// # Examples:
//   !dest : some_transform.unit_axis_x * distance // Go forward along the transform

// # Author(s): Zachary Burke
//---------------------------------------------------------------------------------------

() Vector3
