//---------------------------------------------------------------------------------------
// Waits until this timeline is not playing
//
// Params:
//   poll_secs: 
//     Number of seconds that should be waited between each test 
//     If it is 0.0 it will test every simulation update/frame.
//
// Examples:
//    @timeline._wait_not_playing
//    destroy_something
//
//---------------------------------------------------------------------------------------
(Real poll_secs : 0.1)   
[
  loop
  [
    [exit] when is_playing?.not
    _wait(poll_secs)
  ]
]