//---------------------------------------------------------------------------------------
// + Returns a new RotationAngles that is the sum of itself and the supplied RotationAngles.
//
// # Params:
//   rot: RotationAngles to add
//
// # Returns:
//   new RotationAngles that is the sum of itself and the supplied RotationAngles.
//
// # Examples:
//   rot1 + rot2
//   rot1.add(rot2)
//
// # Author(s): Zachary Burke
//---------------------------------------------------------------------------------------

(RotationAngles rot) RotationAngles

