//---------------------------------------------------------------------------------------
// Class constructor - called when the class is initialized
//
// # Examples:  called by system - do not call yourself
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

()

  [
  // A meter/metre in length in the world co-ordinate system.
  // Unreal uses centimeters as its default unit so a meter is 100cm.  
  @@meter: 100.0
  ]

